export const REQUEST = '_REQUEST'
export const SUCCESS = '_SUCCESS'
export const FAILURE = '_FAILURE'

export const QUERY_SHOW_CONTENT = 'QUERY_SHOW_CONTENT'
export const INPUT_TEXT = 'INPUT_TEXT'
export const BACKGROUND_COLOR = 'BACKGROUND_COLOR'
export const ELEMENT_ENTITY = 'ELEMENT_ENTITY'
export const SELECT_BACKGROUND_IMG = 'SELECT_BACKGROUND_IMG'